spring:
  profiles:
    active: '@activeProfile@'
  jpa:
    properties:
      hibernate:
        show_sql: true
    # Don't do hibernate schema generation since we'll be reading the schema from a file
    # See https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-creating-and-dropping-jpa-databases
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:data
    username: sa
    password:
    schema: schema.sql
